version: "3"

networks:
    inception:

services:
    nginx:
        build: ./requirements/nginx
        image: nginx:v1.0.0
        container_name: nginx
        volumes:
            - wp:/var/www/wordpress
        ports:
            - 443:443
        networks:
            - inception
        restart: always
        env_file: .env
        depends_on:
            - wordpress

    wordpress:
        build: ./requirements/wordpress
        image: wordpress/v1.0.0
        container_name: wordpress
        volumes:
            - wp:/var/www/wordpress
        ports:
            - 9000:9000
        networks:
            - inception
        restart: always
        env_file: .env
        depends_on:
            - mariadb
    
    mariadb:
        build: ./requirements/mariadb
        image: mariadb:v1.0.0
        container_name: mariadb
        volumes:
            - db:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - inception
        restart: always
        env_file: .env

volumes:
    wp:
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: /home/mbeaujar/data/wp
    db:
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: /home/mbeaujar/data/db