version: "3"

networks:
    inception:

services:
    nginx:
        build: ./requirements/nginx
        image: nginx:v1.0.0
        container_name: nginx
        volumes:
            - wp:/var/www/
        ports:
            - 443:443
        networks:
            - inception
        restart: always
        depends_on:
            - wordpress

    ftp:
        build: ./requirements/ftp
        image: ftp:v1.0.0
        container_name: ftp
        ports:
            - "21:21"
            - "20:20"
            - "30020-30030:30020-30030"
        volumes:
            - wp:/home/mbeaujar
        networks:
            - inception
        restart: always
        env_file: .env
        depends_on:
            - nginx
        
    
    redis:
        build: ./requirements/redis
        image: redis:v1.0.0
        container_name: redis
        ports:
            - 6379:6379
        networks:
            - inception
        restart: always
        depends_on:
            - mariadb

    
    wordpress:
        build: ./requirements/wordpress
        image: wordpress:v1.0.0
        container_name: wordpress
        volumes:
            - wp:/var/www/
        ports:
            - 9000:9000
            - 8080:8080
        networks:
            - inception
        restart: always
        env_file: .env
        depends_on:
            - redis
    
    mariadb:
        build: ./requirements/mariadb
        image: mariadb:v1.0.0
        container_name: mariadb
        volumes:
            - db:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - inception
        restart: always
        env_file: .env

volumes:
    wp:
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: /home/mbeaujar/data/wp
    db:
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: /home/mbeaujar/data/db